source("GLS-STEP.R")
check.packages()
RNA<-read.table("RNAtrace1.txt",sep="\t",header=TRUE)
w<-c(seq(10,90,by=10),seq(100,1000,by=25))           
Y<-RNA[,1]
times<-RNA[,2]   
chpt0<-get.zstat(y,times,w)
chpt1<-ChPt(chpt0)
plot.step(chpt0,chpt1,pdfname="RNAFIG1.pdf")
RNA.RESULT1<-get.results(chpt1)
write.table(RNA.RESULT1,file="RNA-RESULT1.txt",sep="\t",header=TRUE)
myModel<-get.model(chpt1,type="bic")
save(myModel,file="All-results-1.Rdata")
#load("All-results-1.Rdata")